CREATE DATABASE TEST;
CREATE DATABASE TEST_PROD;

CREATE USER "test" IDENTIFIED BY "test";
CREATE USER "test_prod" IDENTIFIED BY "test_prod";

GRANT SELECT ON TEST.* TO 'test';
GRANT INSERT ON TEST.* TO 'test';
GRANT UPDATE ON TEST.* TO 'test';
GRANT DELETE ON TEST.* TO 'test';
GRANT CREATE ON TEST.* TO 'test';
GRANT ALTER ON TEST.* TO 'test';
GRANT REFERENCES ON TEST.* TO 'test';
GRANT DROP ON TEST.* TO 'test';
GRANT SELECT ON TEST_PROD.* TO 'test_prod';
GRANT INSERT ON TEST_PROD.* TO 'test_prod';
GRANT UPDATE ON TEST_PROD.* TO 'test_prod';
GRANT DELETE ON TEST_PROD.* TO 'test_prod';
GRANT CREATE ON TEST_PROD.* TO 'test_prod';
GRANT ALTER ON TEST_PROD.* TO 'test_prod';
GRANT REFERENCES ON TEST_PROD.* TO 'test_prod';


